---
velero_chart_version: "12.1.0"
velero_version: "v1.18.2"
velero_plugin_version: "v1.14.2"
velero_bucket: velero-backups
velero_region: garage
velero_s3_url: "http://garage-s3.garage.svc.cluster.local:3900"
velero_s3_access_key: CHANGEME-access
velero_s3_secret_key: CHANGEME-secret
offline_install: false
local_charts_dir: /opt/airgap/charts
