---
- name: Install k8sgpt from local artifact
  ansible.builtin.unarchive:
    src: "{{ local_artifacts_dir }}/k8sgpt.tar.gz"
    dest: /usr/local/bin
    remote_src: yes
  become: yes
  when: offline_install | bool

- name: Install k8sgpt online
  ansible.builtin.get_url:
    url: "https://github.com/k8sgpt-ai/k8sgpt/releases/download/{{ k8sgpt_version }}/k8sgpt_Linux_x86_64.tar.gz"
    dest: /tmp/k8sgpt.tar.gz
    mode: '0644'
  when: not offline_install | bool

- name: Extract k8sgpt online
  ansible.builtin.unarchive:
    src: /tmp/k8sgpt.tar.gz
    dest: /usr/local/bin
    remote_src: yes
  become: yes
  when: not offline_install | bool

- name: Verify k8sgpt
  ansible.builtin.command: k8sgpt version
  changed_when: false
